wandb_version: 1

channels:
  value: 128
dataset:
  value: Cora
edr:
  value: 0
epochs:
  value: 20
fmr:
  value: 0
lr1:
  value: 0.0005
lr2:
  value: 0.001
n_experiments:
  value: 1
n_layers:
  value: 3
split:
  value: PublicSplit
tau:
  value: 0.7
wd1:
  value: 0.01
wd2:
  value: 0.01
