method: grid
metric:
  goal: minimize
  name: best_val_loss
parameters:
  channels:
    values:
    - 128
    - 256
    - 512
    - 1024
  dataset:
    values:
    - Cora
  edr:
    values:
    - 0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
  epochs:
    values:
    - 20
    - 50
    - 100
    - 200
  fmr:
    values:
    - 0
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
  lr1:
    values:
    - 0.0005
    - 0.001
    - 0.005
    - 0.01
  lr2:
    values:
    - 0.001
    - 0.005
    - 0.01
  n_experiments:
    values:
    - 1
  n_layers:
    values:
    - 1
    - 2
  split:
    values:
    - PublicSplit
  tau:
    values:
    - 0.3
    - 0.5
    - 0.7
  wd1:
    values:
    - 0.0001
    - 0.001
    - 0.01
  wd2:
    values:
    - 0.0001
    - 0.001
    - 0.01
