wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
    start_time: 1658467740
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 2
      - 16
      4: 3.9.1
      5: 0.12.21
      8:
      - 5
channels:
  desc: null
  value: 128
dataset:
  desc: null
  value: Cora
edr:
  desc: null
  value: 0
epochs:
  desc: null
  value: 20
fmr:
  desc: null
  value: 0
lr1:
  desc: null
  value: 0.0005
lr2:
  desc: null
  value: 0.001
method:
  desc: null
  value: grid
metric:
  desc: null
  value:
    goal: minimize
    name: best_val_loss
n_experiments:
  desc: null
  value: 1
n_layers:
  desc: null
  value: 2
parameters:
  desc: null
  value:
    channels:
      values:
      - 128
      - 256
      - 512
      - 1024
    dataset:
      values:
      - Cora
    edr:
      values:
      - 0
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
    epochs:
      values:
      - 20
      - 50
      - 100
      - 150
      - 200
    fmr:
      values:
      - 0
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
    lr1:
      values:
      - 0.0005
      - 0.001
      - 0.005
      - 0.01
    lr2:
      values:
      - 0.001
      - 0.005
      - 0.01
    n_experiments:
      values:
      - 1
    n_layers:
      values:
      - 1
      - 2
      - 3
    split:
      values:
      - PublicSplit
    tau:
      values:
      - 0.1
      - 0.3
      - 0.5
      - 0.7
      - 0.9
    wd1:
      values:
      - 0.0005
      - 0.001
      - 0.005
      - 0.01
    wd2:
      values:
      - 0.0001
      - 0.001
      - 0.01
split:
  desc: null
  value: PublicSplit
tau:
  desc: null
  value: 0.9
wd1:
  desc: null
  value: 0.001
wd2:
  desc: null
  value: 0.0001
